version: "3.7"

services:

  tools:
    image: ${REGISTRY}sitecore-docker-tools:${VERSION:-latest}
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BUILD_IMAGE: ${BUILD_IMAGE}